### ISSUE TITLE
레이아웃 분석

### ISSUE THREAD

**Issue by haneu89** [haneu89/pu-admin#1]
상하 또는 좌우 레이아웃을
선택 이유와 예제 들을 첩부하여 결정

**Comment by phkhyun** [comment]
https://colorlib.com//polygon/adminty/default/index.html
http://themetrace.com/demo/chain/index.html

첫번째 예제는 대표님이 처음에 보여주셨던 템플릿으로 사이드메뉴를 접었다 펼쳐지는걸 보시면

한눈에 상하 레이아웃인게 확인되는데 두번째예제 처음봤을땐 좌우인줄 알았다가

열어보니 상하로 나뉘어진 예제였습니다. 일단 제생각은 반응형 때문에 그런거 같은데 

두개 예제 모두 모바일화면이던 pc화면이던 으로 보면 메뉴를 펼치고 접는 

아이콘은 그대로 화면 상단왼쪽에 있고

그 아래 메뉴리스트들이 pc화면에서는 보이지만 모바일크기로 보면 완전히 사라지네요

만약 좌우 레이아웃이라면 메뉴리스트뿐만 아니라 메뉴펼치기아이콘도 사라질거 같아요 

그래서 저희도 반응형으로 만든다고 했으니 상하로 하는게 좋을 것 같아요 !

**Comment by haneu89** [comment]
그럼 상하로 레이아웃을 나누는게 낫겠네요
